version: '3.7'

services:
  backend:
    container_name: hcash_backend
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - '5051:3001'
    depends_on:
      - mongodb
    networks:
      - ${NETWORK}

  mongodb:
    container_name: hcash_mongodb
    image: mongo:latest
    volumes:
      - mongodb-hcash:/data/db
    networks:
      - ${NETWORK}
networks:
  hcash-network:
    driver: bridge
    name: ${NETWORK}

volumes:
  mongodb-hcash:
